# Generated by Django 5.0.1 on 2026-01-22 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Applicant's full name", max_length=200)),
                ('email', models.EmailField(help_text="Applicant's email address", max_length=254)),
                ('phone', models.CharField(help_text="Applicant's phone number", max_length=20)),
                ('position', models.CharField(help_text='Position applied for', max_length=200)),
                ('resume', models.FileField(blank=True, help_text='Resume file (PDF, DOC, or DOCX)', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Submission timestamp')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
