# Generated by Django 4.2.27 on 2026-02-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='reason',
            field=models.CharField(choices=[('service', 'Request for Service'), ('career', 'Join Metavara Technologies'), ('vendor', 'Vendor Registration'), ('general', 'General Inquiry'), ('other', 'Other Requests')], default='general', max_length=50),
        ),
    ]
